/**
 * @fileoverview Data-Driven Achievement & Milestone Definitions
 *
 * Defines all endgame achievements, criteria, rarity tiers, and milestone challenges.
 */

export const ACHIEVEMENT_CATEGORIES = {
  PRODUCTION: "PRODUCTION",
  BOX_OFFICE: "BOX_OFFICE",
  AWARDS: "AWARDS",
  FRANCHISE: "FRANCHISE",
  TALENT: "TALENT",
  SURVIVAL: "SURVIVAL",
  LEGACY: "LEGACY",
};

export const ACHIEVEMENT_RARITIES = {
  COMMON: "COMMON",
  RARE: "RARE",
  EPIC: "EPIC",
  LEGENDARY: "LEGENDARY",
  MYTHIC: "MYTHIC",
};

export const ALL_ACHIEVEMENTS = [
  {
    id: "FIRST_FEATURE",
    name: "Lights, Camera, Action!",
    description: "Release your very first full-length feature film.",
    category: ACHIEVEMENT_CATEGORIES.PRODUCTION,
    rarity: ACHIEVEMENT_RARITIES.COMMON,
    icon: "Film",
    maxProgress: 1,
    check: (stats) => (stats.moviesReleased || 0) >= 1,
  },
  {
    id: "FIRST_HIT",
    name: "Crowd Pleaser",
    description: "Deliver your studio's first box office HIT.",
    category: ACHIEVEMENT_CATEGORIES.BOX_OFFICE,
    rarity: ACHIEVEMENT_RARITIES.COMMON,
    icon: "TrendingUp",
    maxProgress: 1,
    check: (stats) => (stats.hitMovies || 0) >= 1,
  },
  {
    id: "BLOCKBUSTER_TITAN",
    name: "Blockbuster Titan",
    description: "Produce a certified BLOCKBUSTER film.",
    category: ACHIEVEMENT_CATEGORIES.BOX_OFFICE,
    rarity: ACHIEVEMENT_RARITIES.RARE,
    icon: "Zap",
    maxProgress: 1,
    check: (stats) => (stats.blockbusters || 0) >= 1,
  },
  {
    id: "ALL_TIME_LEGEND",
    name: "Cinematic Eternity",
    description: "Deliver an ALL-TIME BLOCKBUSTER that redefines industry history.",
    category: ACHIEVEMENT_CATEGORIES.BOX_OFFICE,
    rarity: ACHIEVEMENT_RARITIES.MYTHIC,
    icon: "Sparkles",
    maxProgress: 1,
    check: (stats) => (stats.allTimeBlockbusters || 0) >= 1,
  },
  {
    id: "BOX_OFFICE_BILLIONAIRE",
    name: "Billion-Rupee Empire",
    description: "Accumulate over ₹1,000,000,000 in total lifetime box office earnings.",
    category: ACHIEVEMENT_CATEGORIES.BOX_OFFICE,
    rarity: ACHIEVEMENT_RARITIES.EPIC,
    icon: "DollarSign",
    maxProgress: 1000000000,
    check: (stats) => (stats.totalBoxOffice || 0) >= 1000000000,
    getProgress: (stats) => Math.min(1000000000, stats.totalBoxOffice || 0),
  },
  {
    id: "ACADEMY_GLORY",
    name: "Golden Statuette",
    description: "Win your first prestigious Annual Film Award.",
    category: ACHIEVEMENT_CATEGORIES.AWARDS,
    rarity: ACHIEVEMENT_RARITIES.RARE,
    icon: "Award",
    maxProgress: 1,
    check: (stats) => (stats.totalAwards || 0) >= 1,
  },
  {
    id: "TRIPLE_CROWN",
    name: "Triple Crown Academy",
    description: "Win 3 or more Academy awards across your studio's catalog.",
    category: ACHIEVEMENT_CATEGORIES.AWARDS,
    rarity: ACHIEVEMENT_RARITIES.EPIC,
    icon: "Trophy",
    maxProgress: 3,
    check: (stats) => (stats.totalAwards || 0) >= 3,
    getProgress: (stats) => Math.min(3, stats.totalAwards || 0),
  },
  {
    id: "FRANCHISE_MASTERY",
    name: "Cinematic Universe",
    description: "Establish a thriving franchise with at least 3 successful installments.",
    category: ACHIEVEMENT_CATEGORIES.FRANCHISE,
    rarity: ACHIEVEMENT_RARITIES.EPIC,
    icon: "Layers",
    maxProgress: 3,
    check: (stats) => (stats.maxFranchiseInstallments || 0) >= 3,
    getProgress: (stats) => Math.min(3, stats.maxFranchiseInstallments || 0),
  },
  {
    id: "LIVING_LEGEND_MENTOR",
    name: "Hall of Legends",
    description: "Have an actor reach Living Legend / Legacy status under your management.",
    category: ACHIEVEMENT_CATEGORIES.TALENT,
    rarity: ACHIEVEMENT_RARITIES.EPIC,
    icon: "Star",
    maxProgress: 1,
    check: (stats) => (stats.legacyTalentCount || 0) >= 1,
  },
  {
    id: "DECADE_SURVIVOR",
    name: "Decade of Dominance",
    description: "Guide your studio through 10 full simulated years (520 weeks).",
    category: ACHIEVEMENT_CATEGORIES.SURVIVAL,
    rarity: ACHIEVEMENT_RARITIES.RARE,
    icon: "Clock",
    maxProgress: 520,
    check: (stats) => (stats.currentWeek || 0) >= 520,
    getProgress: (stats) => Math.min(520, stats.currentWeek || 0),
  },
  {
    id: "GOLDEN_ERA_50",
    name: "The Golden Era",
    description: "Simulate 50 years (2600 weeks) of cinematic history and studio leadership.",
    category: ACHIEVEMENT_CATEGORIES.LEGACY,
    rarity: ACHIEVEMENT_RARITIES.MYTHIC,
    icon: "Crown",
    maxProgress: 2600,
    check: (stats) => (stats.currentWeek || 0) >= 2600,
    getProgress: (stats) => Math.min(2600, stats.currentWeek || 0),
  },
  {
    id: "SURVIVED_BANKRUPTCY",
    name: "Phoenix Rising",
    description: "Recover your studio from financial crisis back to profitability and high prestige.",
    category: ACHIEVEMENT_CATEGORIES.SURVIVAL,
    rarity: ACHIEVEMENT_RARITIES.LEGENDARY,
    icon: "Flame",
    maxProgress: 1,
    check: (stats) => stats.recoveredFromCrisis === true,
  },
];
